from typing import Protocol

from project_service.projects.models import Project


class ProjectRepository(Protocol):
    """Persistence-neutral project repository contract."""

    def add(self, project: Project) -> Project: ...
    def get(self, project_id: str, *, for_update: bool = False) -> Project | None: ...
    def list_for_actor(self, actor_id: str) -> list[Project]: ...
    def next_business_no(self) -> str: ...
    def save(self, project: Project, expected_version: int) -> bool: ...
