"""Task persistence contracts."""

from __future__ import annotations

from datetime import date
from typing import Protocol

from project_service.tasks.models import Task, Worklog


class TaskRepository(Protocol):
    def get(
        self, project_id: str, resource_id: str, *, for_update: bool = False
    ) -> Task | None: ...
    def list(
        self,
        project_id: str,
        limit: int = 50,
        after: tuple[str, str] | None = None,
    ) -> list[Task]: ...
    def has_open_tasks(self, project_id: str, scope_type: str, scope_id: str) -> bool: ...
    def add(self, task: Task) -> None: ...
    def save(self, task: Task, expected_version: int) -> bool: ...
    def next_business_no(self) -> str: ...
    def get_worklog(self, project_id: str, task_id: str, worklog_id: str) -> Worklog | None: ...
    def list_worklogs(self, project_id: str, task_id: str) -> list[Worklog]: ...
    def append_worklog(self, worklog: Worklog) -> None: ...
    def sum_task_minutes(self, project_id: str, task_id: str) -> int: ...
    def sum_user_day_minutes(self, project_id: str, user_id: str, work_date: date) -> int: ...
    def lock_worklog_scope(self, project_id: str, user_id: str, work_date: date) -> None: ...
