import 'vuetify/styles';
import './styles/tokens.css';
import './styles/global.css';
import { createApp } from 'vue';
import { createPinia } from 'pinia';
import { createVuetify } from 'vuetify';
import * as components from 'vuetify/components';
import * as directives from 'vuetify/directives';
import App from './App.vue';
import router from './router';
createApp(App).use(createPinia()).use(router).use(createVuetify({ components, directives, theme: { defaultTheme: 'light' } })).mount('#app');
