"""Collaboration persistence contracts."""

from __future__ import annotations

from typing import Protocol

from project_service.collaboration.models import Iteration, ProjectMembership, ReleaseVersion


class CollaborationRepository(Protocol):
    def get_active_membership(
        self, project_id: str, user_id: str, *, for_update: bool = False
    ) -> ProjectMembership | None: ...
    def get_membership(
        self, project_id: str, membership_id: str, *, for_update: bool = False
    ) -> ProjectMembership | None: ...
    def list_members(self, project_id: str) -> list[ProjectMembership]: ...
    def add_membership(self, membership: ProjectMembership) -> None: ...
    def save_membership(self, membership: ProjectMembership, expected_version: int) -> bool: ...
    def transfer_owner_roles(
        self,
        project_id: str,
        current_id: str,
        target_id: str,
        current_version: int,
        target_version: int,
    ) -> bool: ...
    def get_version(
        self, project_id: str, resource_id: str, *, for_update: bool = False
    ) -> ReleaseVersion | None: ...
    def list_versions(self, project_id: str) -> list[ReleaseVersion]: ...
    def add_version(self, version: ReleaseVersion) -> None: ...
    def save_version(self, version: ReleaseVersion, expected_version: int) -> bool: ...
    def get_iteration(
        self, project_id: str, resource_id: str, *, for_update: bool = False
    ) -> Iteration | None: ...
    def list_iterations(self, project_id: str) -> list[Iteration]: ...
    def add_iteration(self, iteration: Iteration) -> None: ...
    def save_iteration(self, iteration: Iteration, expected_version: int) -> bool: ...
    def next_counter(self, project_id: str, counter_type: str) -> int: ...
